version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_rss_aggregator
      MYSQL_USER: go
      MYSQL_PASSWORD: go
    ports:
      - 3306:3306
    # networks:
    #   - public # Only needed for local development
    #   - private
    volumes:
      - ./docker-data/volumes/mysql:/var/lib/mysql
networks:
  public:
  private:
    internal: true
