[mysql]
server = "localhost"
port = 3306
database = "go_rss_aggregator"
user = "rss_db_user"
password = "GO_MYSQL_PASSWD"

[dbmigrations]
files = "db-migrations/"

[server]
port = 8080

[logger]
level = "info"
encoding = "json"
outputPaths = ["stdout"]
errorOutputPaths = ["stderr"]

[logger.encoderconfig]
messageKey = "message"
levelEncoder = "lowercase"